### ISSUE TITLE
Save User Calculated Score

### ISSUE THREAD

**Issue by lamontenunn** [lamontenunn/ACFT-CALC#14]
**User Story:**

"As a Solider I would like to ability to view my previously entered scores an have them display some where (preferably the homepage)"

**Tasks:**

- [ ] Implement a way to store user's local data in a database
- [ ] Add a save button to the calculator page.
- [ ] When a user clicks calculate then save the score gets added to the database
- [ ] Design a unique UI for the homepage to display user's previous score

**Acceptance Criteria:**
- User can view their scores via the homepage
- Shows previous 6 saved scores
- User can view a entire list of all saved scores

**Acceptance Tests:**
### TBD
